Repository rungalileo/docs-official, pull requests merged in 2025-05, with the labels that each got.

#133 design callout component + add link to npm + pypi packages.
  sdk-api/python/overview.mdx
  sdk-api/typescript/overview.mdx
  snippets/components/info-note.mdx
Labels: documentation

#136 Datasets: Add prompt template, clean up language, improve best practices
  concepts/datasets.mdx
Labels: documentation, datasets

#135 Add clarification on OpenAI usage
  concepts/datasets.mdx
  concepts/playground.mdx
  getting-started/experiments/datasets.mdx
  getting-started/experiments/running-experiments-in-console.mdx
  getting-started/experiments/running-experiments.mdx
  getting-started/quickstart.mdx
  guides/logs/openai-agents.mdx
  how-to-guides/conversational-ai/instruction-adherence.mdx
  how-to-guides/conversational-ai/reducing-hesitation-and-uncertainty.mdx
  how-to-guides/rag/basic-example.mdx
  integrations/otel.mdx
  references/faqs/errors.mdx
  snippets/Screenshot.mdx
  snippets/code/python/getting-started/getting-started-1.mdx
  snippets/code/typescript/getting-started/getting-started-1.mdx
Labels: documentation

#137 Typescript Corrections: added (input: any) to make the linters happy 🍾
  snippets/code/typescript/experiments/custom-dataset.mdx
  snippets/code/typescript/experiments/existing-dataset.mdx
  snippets/code/typescript/sdk/datasets/custom-datasets.mdx
  snippets/code/typescript/sdk/datasets/experiments.mdx
  snippets/code/typescript/sdk/experiments/custom-dataset.mdx
  snippets/code/typescript/sdk/experiments/runner-function.mdx
  snippets/code/typescript/sdk/logging/log-wrapper-basic.mdx
  snippets/code/typescript/sdk/logging/log-wrapper-example.mdx
  snippets/code/typescript/sdk/wrappers/openai-log-function.mdx
Labels: documentation

#140 Create agent langchain cookbook
  cookbooks/use-cases/agent-langchain.mdx
  docs.json
Labels: documentation, agentic-ai, cookbook

#152 nits to make the .mdx linters happy :)
  .vscode/settings.json
  README.md
Labels: documentation, Nit

#160 docs: SC-28391: Note to require saved datasets for prompt template experiments
  sdk-api/python/experiments.mdx
  sdk-api/typescript/experiments.mdx
  snippets/code/python/concepts/experiments/prompt.mdx
Labels: documentation
